name: Release
on:
  push:
    branches: [master, main, configure-sonatype]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Set up GPG
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 --decode > private.key
          gpg --import --batch private.key
          rm private.key
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      - name: Clean SBT cache
        run: sbt clean
      - name: Run sbt publish
        run: |
          sbt sonatypeOpen "ru.d10xa"
          sbt publishSigned
          sbt sonatypeClose "ru.d10xa"
          sbt sonatypeRelease "ru.d10xa"
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
