name: Release
on:
  push:
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - run: sbt -debug -Dsun.net.client.defaultReadTimeout=60000 -Dsun.net.client.defaultConnectTimeout=60000 -Divy.http.connectionTimeout=60000 -Divy.http.timeout=60000 -Divy.http.readTimeout=60000-v ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Upload bundle artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: sonatype-bundle
          path: target/sonatype-staging/0.3.0-bundle/bundle.zip
#      - name: Set up GPG
#        run: |
#          echo "${{ secrets.PGP_SECRET }}" | base64 --decode > private.key
#          gpg --import --batch private.key
#          rm private.key
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#      - name: Run sbt publish
#        run: |
#          sbt sonatypeBundleRelease
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
