name: Release
on:
  push:
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - run: sbt "project jsonLogViewerJVM" ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#      - name: Set up GPG
#        run: |
#          echo "${{ secrets.PGP_SECRET }}" | base64 --decode > private.key
#          gpg --import --batch private.key
#          rm private.key
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#      - name: Run sbt publish
#        run: |
#          sbt sonatypeBundleRelease
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
