name: Release
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Set up GPG
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 --decode > private.key
          gpg --import --batch private.key
          rm private.key
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      - name: Run sbt publish
        run: |
          sbt ++3.5.0 json-log-viewerJVM/publishSigned
          sbt ++3.5.0 json-log-viewerJVM/sonatypeBundleRelease
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
